### PR TITLE
Update project dependencies

### PR DESCRIPTION
**Pull request by the-og-gear**
Previous PR was borked because I actually opened the csproj instead. lol. Anyways here's this. Dependencies are updated and all features seem to be in working order[^1].

We've updated Discord.Net dependencies to provide the latest and greatest features to developers. Among these include slash commands, guild avatars, thread support, timeouts, and more! With the changes required to the local copy of Discord.Addons.Interactive, we should be able to further update dependencies with minimal issue in the future[^2].

I'll keep my local branch around and provide updates through it in the future if I see stuff fall too far back. <3

[^1]: Updates come without warranty, please perform your own testing to ensure stuff isn't absurdly broken that I was unable to catch.
[^2]: Perform updates at your own risk. Make sure updates are compatible and don't break things in major ways.

### CODE REVIEW

**Comment by Ahndrek-LiCyri** [comment]
I'm going to give this a bump/confirm.

The bot really should be up to modern discord API standards and use guilds.

**Comment by the-og-gear** [comment]
It's only further out of date the longer this takes to be merged. Access to various additional features for bots and/or accounts implemented after this PR was made won't be available with this one, however our primary focus would be using slash commands from this.

**Comment by Shelme74** [comment]
If needed since I'm currently in vacation, I can work on it as I got free time.

**Comment by the-og-gear** [comment]
There shouldn't be anything else to do for the actual updating of dependencies. It's the command structure after the update that needs reworked to allow for slash commands to be registered.

**Comment by Shelme74** [comment]
I can try to work on it if you need a hand

**Comment by the-og-gear** [comment]
Bump. Over a year old now, bot is still not using Discord's standards for bots...

**Comment by iShauny** [comment]
thanks! I have merged these suggestions into PR https://github.com/bealsbe/Floofbot/pull/169 as there was still an issue or two so I'll close this off - but this was very helpful for updating the dependencies

**Pull request closed without merging**
